In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import quandl as ql
import os
import pandas as pd
import pandas_market_calendars as mcal
from datetime import datetime, date, timedelta
import requests

In [2]:
ql.ApiConfig.api_key = 'dVe83AYozj9EP9GduQZZ'

In [22]:
#fetch 30 days of data
today = date.today()
begDate= today - timedelta(days=7)
endDate = today
actions_df=ql.get_table('SHARADAR/ACTIONS',  date={'gte': begDate, 'lte': endDate})
display(actions_df)

,date,action,ticker,name,value,contraticker,contraname
None,,,,,,,
0,2026-03-24,relation,ZOOZW,ZOOZ STRATEGY LTD,NaN,ZOOZ,ZOOZ STRATEGY LTD
1,2026-03-24,relation,ZOOZ,ZOOZ STRATEGY LTD,NaN,ZOOZW,ZOOZ STRATEGY LTD
2,2026-03-24,relation,ZKPU,LAFAYETTE DIGITAL ACQUISITION CORP I,NaN,ZKP,LAFAYETTE DIGITAL ACQUISITION CORP I
3,2026-03-24,relation,ZKP,LAFAYETTE DIGITAL ACQUISITION CORP I,NaN,ZKPU,LAFAYETTE DIGITAL ACQUISITION CORP I
4,2026-03-24,relation,ZIONP,ZIONS BANCORPORATION NATIONAL ASSOCIATION,NaN,ZION,ZIONS BANCORPORATION NATIONAL ASSOCIATION
...,...,...,...,...,...,...,...
3312,2026-03-18,dividend,BPOP,POPULAR INC,0.7500,N/A,N/A
3313,2026-03-18,dividend,BITX,2X BITCOIN STRATEGY ETF,0.0165,N/A,N/A
3314,2026-03-18,listed,BHDG,NICHOLAS BITCOIN TAIL ETF,NaN,BHDG,N/A
3315,2026-03-18,dividend,ARHS,ARHAUS INC,0.3500,N/A,N/A
3316,2026-03-18,dividend,AAON,AAON INC,0.1000,N/A,N/A

In [23]:
# get peer data, filter for quality score
df = pd.read_csv('peerData.csv')
df = df.sort_values(by='qualityScore', ascending=False)
df_quality=df.loc[df['qualityScore']>=0.5]
tick_quality=df_quality.ticker.to_list()
display(df_quality.head())
print(tick_quality)

,companyId,ticker,quarter,industry,industryFull,qualityScore,earningsScore,opportunityScore,fqRevSegmentEstBeatCompoundBeforeEarningsScore,fqRevSegmentGrowthAvg2yCompoundScore,...,balanceSheetHealthGlobalCheck,balanceSheetInterestCoverageCheck,balanceSheetPositiveEbitdaCheck,cashBurn2y,fqArrYoyGrowthAvg,fqBillingsYoyGrowthAvg,fqNetDebt,fqNetIntExp,ltmNetIntExp,ltmOpMarg
1066,1622,APH,Q4/2025,business_services,business_services.tech_hardware_and_electronic...,0.969869,0.571364,0.126247,NaN,NaN,...,1.0,1,1.0,-8.756200e+09,NaN,NaN,4.067800e+09,-129700000.0,-367800000.0,0.254110
105,163,APP,Q4/2025,saas,saas.sales_and_marketing_software.advertising_...,0.917809,0.605630,0.014943,NaN,NaN,...,1.0,1,1.0,-7.942188e+09,NaN,NaN,1.057645e+09,-51290000.0,-207016000.0,0.757549
517,805,VRT,Q4/2025,industrials,industrials.electrical_equipment.electrical_sy...,0.905703,0.316067,-0.011526,NaN,NaN,...,1.0,1,1.0,-3.826800e+09,NaN,NaN,1.184600e+09,-16700000.0,-86100000.0,0.178858
21,31,PLTR,Q4/2025,saas,saas.data_and_analytics_software.data_analytics,0.901112,0.897273,0.000000,NaN,NaN,...,1.0,1,1.0,-4.540872e+09,NaN,0.594612,-6.947705e+09,-45989000.0,-209274000.0,0.315950
901,1426,RDDT,Q4/2025,consumer_internet,consumer_internet.social_networking,0.894688,0.771596,0.123814,NaN,NaN,...,1.0,1,1.0,-1.368338e+09,NaN,NaN,-2.453597e+09,22947000.0,86722000.0,0.200673

['APH', 'APP', 'VRT', 'PLTR', 'RDDT', 'NVDA', 'PLMR', 'FIX', 'LLY', 'SMCI', 'PSTG', 'HLNE', 'IBKR', 'GSHD', 'POWL', 'MTDR', 'FOUR', 'BOW', 'LPLA', 'FTAI', 'KKR', 'EXE', 'CSW', 'STRL', 'BMI', 'TDG', 'FSLR', 'HCI', 'FANG', 'HWM', 'WT', 'NXT', 'CHRD', 'RYAN', 'EOG', 'MELI', 'GE', 'NU', 'APO', 'PL', 'EXLS', 'HURN', 'PAR', 'AWI', 'MA', 'SYF', 'KNSL', 'PGR', 'OWL', 'AVGO', 'PR', 'AGX', 'HEI', 'MVST', 'ESE', 'MPWR', 'EVLV', 'GHM', 'AX', 'FSS', 'TT', 'FICO', 'MORN', 'ENVA', 'BWIN', 'ROAD', 'DDOG', 'WING', 'KNTK', 'CASH', 'EQT', 'OSCR', 'UI', 'HOOD', 'META', 'IOT', 'EME', 'LRN', 'PAY', 'MNST', 'AXP', 'BE', 'DASH', 'SE', 'EVGO', 'BYRN', 'OSIS', 'COP', 'HLI', 'RELY', 'TALO', 'VG', 'MNDY', 'SPXC', 'AJG', 'TPL', 'PWR', 'DY', 'ARES', 'SEIC', 'V', 'ALHC', 'ANF', 'RBC', 'CTRA', 'MU', 'MSI', 'NIC', 'GOOGL', 'GRAB', 'GTLS', 'SHOP', 'CBZ', 'SNOW', 'BRO', 'WTS', 'TW', 'CTAS', 'KLAC', 'LULU', 'NTRA', 'FCEL', 'ZS', 'QNST', 'BWMN', 'LRCX', 'ATRO', 'EVR', 'DVN', 'MSFT', 'DUOL', 'CRWD', 'PM', 'RBA', 'GTLB', 'NVMI', 'ZETA', 'AXON', 'PODD', 'MLI', 'CCB', 'NOG', 'IMAX', 'LC', 'ERIE', 'PAYO', 'EEFT', 'BLBD', 'ABNB', 'AMSC', 'PRIM']

In [24]:
# get action lists
set(actions_df['action'].to_list())

{'bankruptcyliquidation',
 'delisted',
 'dividend',
 'listed',
 'regulatorydelisting',
 'relation',
 'split',
 'tickerchangefrom',
 'tickerchangeto'}

In [26]:
alert_df=actions_df[actions_df['ticker'].isin(tick_quality)].reset_index(drop=True)
alert_df.set_index(['ticker'], inplace=True, drop=True)
alert_df=alert_df[alert_df['action'].isin(['split', 'delisted', 'listed', 'regulatorydelisting', 'voluntarydelisting','tickerchangedfrom', 'tickerchangedto', 'spinoff', 'split', 'spunofffrom','dividend'])]
display(alert_df)

,date,action,name,value,contraticker,contraname
ticker,,,,,,
AVGO,2026-03-23,dividend,BROADCOM INC,0.65,N/A,N/A
APH,2026-03-23,dividend,AMPHENOL CORP,0.25,N/A,N/A
MSI,2026-03-20,dividend,MOTOROLA SOLUTIONS INC,1.21,N/A,N/A
HLNE,2026-03-20,dividend,HAMILTON LANE INC,0.54,N/A,N/A
PM,2026-03-19,dividend,PHILIP MORRIS INTERNATIONAL INC,1.47,N/A,N/A