In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import quandl as ql
import os
import pandas as pd
import pandas_market_calendars as mcal
from datetime import datetime, date, timedelta
import requests

In [13]:
ql.ApiConfig.api_key = 'dVe83AYozj9EP9GduQZZ'

In [ ]:
event_codes = {11: 'Entry into a Material Definitive Agreement', 
12: 'Termination of a Material Definitive Agreement',
13: 'Bankruptcy or Receivership',
14: 'Mine Safety Reporting of Shutdowns Patterns of Violations',
15: 'Receipt of an Attorneys Written Notice Pursuant to 17 CFR 205.3d',
21: 'Completion of Acquisition or Disposition of Assets',
22: 'Results of Operations and Financial Condition',
23: 'Creation of a Direct Financial Obligation/an Obligation under an Off-Balance Sheet Arrangement of a Registrant',
24: 'Triggering Events That Accelerate or Increase a Direct Financial Obligation or an Obligation under an Off-Balance Sheet Arrangement',
25: 'Cost Associated with Exit or Disposal Activities',
26: 'Material Impairments',
31: 'Notice of Delisting or Failure to Satisfy a Continued Listing Rule or Standard; Transfer of Listing',
32: 'Unregistered Sales of Equity Securities',
33: 'Material Modifications to Rights of Security Holders',
34: 'Schedule 13G Filing',
35: 'Schedule 13D Filing',
36: 'Notice under Rule 12b25 of inability to timely file all or part of a Form 10-K or 10-Q',
40: 'Changes in Registrants Certifying Accountant',
41: 'Changes in Registrants Certifying Accountant',
42: 'Non-Reliance on Previously Issued Financial Statements or a Related Audit Report or Completed Interim Review',
51: 'Changes in Control of Registrant',
52: 'Departure of Directors or Certain Officers; Election of Directors; Appointment of Certain Officers: Compensatory Arrangements of Certain Officers',
53: 'Amendments to Articles of Incorporation or Bylaws; and/or Change in Fiscal Year',
54: 'Temporary Suspension of Trading Under Registrants Employee Benefit Plans',
55: 'Amendments to the Registrants Code of Ethics; or Waiver of a Provision of the Code of Ethics',
56: 'Change in Shell Company Status',
57: 'Submission of Matters to a Vote of Security Holders',
58: 'Shareholder Nominations Pursuant to Exchange Act Rule 14a-11',
61: 'ABS Informational and Computational Material',
62: 'Change of Servicer or Trustee',
63: 'Change in Credit Enhancement or Other External Support',
64: 'Failure to Make a Required Distribution',
65: 'Securities Act Updating Disclosure',
71: 'Regulation FD Disclosure',
81: 'Other Events',
91: 'Financial Statements and Exhibits'}

In [ ]:
#get 1 wk of data
today = date.today()
begDate= today - timedelta(days=7)
endDate = today
events_df=ql.get_table('SHARADAR/EVENTS',  date={'gte': begDate, 'lte': endDate})
display(events_df)

     ticker       date eventcodes
None
0      ZVRA 2026-03-09   22|52|91
1      ZURA 2026-03-10      71|91
2      ZUMZ 2026-03-12   22|81|91
3       ZTO 2026-03-11         81
4      ZTEK 2026-03-13         81
...     ...        ...        ...
1443   AAUC 2026-03-09         81
1444   AAPG 2026-03-11         81
1445    AAP 2026-03-10   52|71|91
1446   AAOI 2026-03-12      11|91
1447    AAL 2026-03-09   11|23|91

[1448 rows x 3 columns]

In [ ]:
#get peer data and filter for quality score
df = pd.read_csv('peerData.csv')
df = df.sort_values(by='qualityScore', ascending=False)
df_quality=df.loc[df['qualityScore']>=0.5]
tick_quality=df_quality.ticker.to_list()
display(df_quality.head())
print(tick_quality)

,companyId,ticker,quarter,industry,industryFull,qualityScore,earningsScore,opportunityScore,fqRevSegmentEstBeatCompoundBeforeEarningsScore,fqRevSegmentGrowthAvg2yCompoundScore,...,balanceSheetHealthGlobalCheck,balanceSheetInterestCoverageCheck,balanceSheetPositiveEbitdaCheck,cashBurn2y,fqArrYoyGrowthAvg,fqBillingsYoyGrowthAvg,fqNetDebt,fqNetIntExp,ltmNetIntExp,ltmOpMarg
1066,1622,APH,Q4/2025,business_services,business_services.tech_hardware_and_electronic...,0.969869,0.571364,0.126247,NaN,NaN,...,1.0,1,1.0,-8.756200e+09,NaN,NaN,4.067800e+09,-129700000.0,-367800000.0,0.254110
105,163,APP,Q4/2025,saas,saas.sales_and_marketing_software.advertising_...,0.917809,0.605630,0.014943,NaN,NaN,...,1.0,1,1.0,-7.942188e+09,NaN,NaN,1.057645e+09,-51290000.0,-207016000.0,0.757549
517,805,VRT,Q4/2025,industrials,industrials.electrical_equipment.electrical_sy...,0.905703,0.316067,-0.011526,NaN,NaN,...,1.0,1,1.0,-3.826800e+09,NaN,NaN,1.184600e+09,-16700000.0,-86100000.0,0.178858
21,31,PLTR,Q4/2025,saas,saas.data_and_analytics_software.data_analytics,0.901112,0.897273,0.000000,NaN,NaN,...,1.0,1,1.0,-4.540872e+09,NaN,0.594612,-6.947705e+09,-45989000.0,-209274000.0,0.315950
901,1426,RDDT,Q4/2025,consumer_internet,consumer_internet.social_networking,0.894688,0.771596,0.123814,NaN,NaN,...,1.0,1,1.0,-1.368338e+09,NaN,NaN,-2.453597e+09,22947000.0,86722000.0,0.200673

['APH', 'APP', 'VRT', 'PLTR', 'RDDT', 'NVDA', 'PLMR', 'FIX', 'LLY', 'SMCI', 'PSTG', 'HLNE', 'IBKR', 'GSHD', 'POWL', 'MTDR', 'FOUR', 'BOW', 'LPLA', 'FTAI', 'KKR', 'EXE', 'CSW', 'STRL', 'BMI', 'TDG', 'FSLR', 'HCI', 'FANG', 'HWM', 'WT', 'NXT', 'CHRD', 'RYAN', 'EOG', 'MELI', 'GE', 'NU', 'APO', 'PL', 'EXLS', 'HURN', 'PAR', 'AWI', 'MA', 'SYF', 'KNSL', 'PGR', 'OWL', 'AVGO', 'PR', 'AGX', 'HEI', 'MVST', 'ESE', 'MPWR', 'EVLV', 'GHM', 'AX', 'FSS', 'TT', 'FICO', 'MORN', 'ENVA', 'BWIN', 'ROAD', 'DDOG', 'WING', 'KNTK', 'CASH', 'EQT', 'OSCR', 'UI', 'HOOD', 'META', 'IOT', 'EME', 'LRN', 'PAY', 'MNST', 'AXP', 'BE', 'DASH', 'SE', 'EVGO', 'BYRN', 'OSIS', 'COP', 'HLI', 'RELY', 'TALO', 'VG', 'MNDY', 'SPXC', 'AJG', 'TPL', 'PWR', 'DY', 'ARES', 'SEIC', 'V', 'ALHC', 'ANF', 'RBC', 'CTRA', 'MU', 'MSI', 'NIC', 'GOOGL', 'GRAB', 'GTLS', 'SHOP', 'CBZ', 'SNOW', 'BRO', 'WTS', 'TW', 'CTAS', 'KLAC', 'LULU', 'NTRA', 'FCEL', 'ZS', 'QNST', 'BWMN', 'LRCX', 'ATRO', 'EVR', 'DVN', 'MSFT', 'DUOL', 'CRWD', 'PM', 'RBA', 'GTLB', 'NVMI', 'ZETA', 'AXON', 'PODD', 'MLI', 'CCB', 'NOG', 'IMAX', 'LC', 'ERIE', 'PAYO', 'EEFT', 'BLBD', 'ABNB', 'AMSC', 'PRIM']

In [ ]:
#swap out event codes
alert_df=events_df[events_df['ticker'].isin(tick_quality)].reset_index()
alert_df['events']=alert_df['eventcodes'].str.split('|', expand=False)
alert_df = alert_df.explode('events', ignore_index=True)
alert_df['eventname'] = alert_df['events'].astype(int)
alert_df['eventname'] = alert_df['eventname'].map(event_codes)
MA_alert_df = alert_df[alert_df['events']=='11']
# alert_df=alert_df.set_index['ticker']
display(alert_df)
display(MA_alert_df)

,None,ticker,date,eventcodes,events,eventname
0,67,WING,2026-03-11,81|91,81,Other Events
1,67,WING,2026-03-11,81|91,91,Financial Statements and Exhibits
2,122,VG,2026-03-13,11|23|81|91,11,Entry into a Material Definitive Agreement
3,122,VG,2026-03-13,11|23|81|91,23,Creation of a Direct Financial Obligation/an O...
4,122,VG,2026-03-13,11|23|81|91,81,Other Events
5,122,VG,2026-03-13,11|23|81|91,91,Financial Statements and Exhibits
6,245,SYF,2026-03-09,71|91,71,Regulation FD Disclosure
7,245,SYF,2026-03-09,71|91,91,Financial Statements and Exhibits
8,406,RBA,2026-03-09,81|91,81,Other Events
9,406,RBA,2026-03-09,81|91,91,Financial Statements and Exhibits
10,415,QNST,2026-03-13,91,91,Financial Statements and Exhibits
11,448,PODD,2026-03-12,71|91,71,Regulation FD Disclosure
12,448,PODD,2026-03-12,71|91,91,Financial Statements and Exhibits
13,452,PM,2026-03-13,71|91,71,Regulation FD Disclosure
14,452,PM,2026-03-13,71|91,91,Financial Statements and Exhibits
15,484,PAY,2026-03-13,52|91,52,Departure of Directors or Certain Officers; El...
16,484,PAY,2026-03-13,52|91,91,Financial Statements and Exhibits
17,561,NOG,2026-03-13,81|91,81,Other Events
18,561,NOG,2026-03-13,81|91,91,Financial Statements and Exhibits
19,605,MSI,2026-03-12,52|91,52,Departure of Directors or Certain Officers; El...
20,605,MSI,2026-03-12,52|91,91,Financial Statements and Exhibits
21,612,MORN,2026-03-13,81|91,81,Other Events
22,612,MORN,2026-03-13,81|91,91,Financial Statements and Exhibits
23,733,KLAC,2026-03-12,71|81,71,Regulation FD Disclosure
24,733,KLAC,2026-03-12,71|81,81,Other Events
25,827,HWM,2026-03-10,71|91,71,Regulation FD Disclosure
26,827,HWM,2026-03-10,71|91,91,Financial Statements and Exhibits
27,945,FOUR,2026-03-09,52|71,52,Departure of Directors or Certain Officers; El...
28,945,FOUR,2026-03-09,52|71,71,Regulation FD Disclosure
29,964,FICO,2026-03-11,81|91,81,Other Events
30,964,FICO,2026-03-11,81|91,91,Financial Statements and Exhibits
31,975,FCEL,2026-03-09,22|71|91,22,Results of Operations and Financial Condition
32,975,FCEL,2026-03-09,22|71|91,71,Regulation FD Disclosure
33,975,FCEL,2026-03-09,22|71|91,91,Financial Statements and Exhibits
34,979,FANG,2026-03-12,11|81|91,11,Entry into a Material Definitive Agreement
35,979,FANG,2026-03-12,11|81|91,81,Other Events
36,979,FANG,2026-03-12,11|81|91,91,Financial Statements and Exhibits
37,986,EVLV,2026-03-10,22|91,22,Results of Operations and Financial Condition
38,986,EVLV,2026-03-10,22|91,91,Financial Statements and Exhibits
39,998,EQT,2026-03-10,81|91,81,Other Events
40,998,EQT,2026-03-10,81|91,91,Financial Statements and Exhibits
41,1039,DY,2026-03-10,91,91,Financial Statements and Exhibits
42,1108,CTAS,2026-03-11,11|71|81|91,11,Entry into a Material Definitive Agreement
43,1108,CTAS,2026-03-11,11|71|81|91,71,Regulation FD Disclosure
44,1108,CTAS,2026-03-11,11|71|81|91,81,Other Events
45,1108,CTAS,2026-03-11,11|71|81|91,91,Financial Statements and Exhibits
46,1195,CCB,2026-03-12,52|91,52,Departure of Directors or Certain Officers; El...
47,1195,CCB,2026-03-12,52|91,91,Financial Statements and Exhibits
48,1211,BYRN,2026-03-09,22|91,22,Results of Operations and Financial Condition
49,1211,BYRN,2026-03-09,22|91,91,Financial Statements and Exhibits
50,1264,BLBD,2026-03-11,52|57|91,52,Departure of Directors or Certain Officers; El...
51,1264,BLBD,2026-03-11,52|57|91,57,Submission of Matters to a Vote of Security Ho...
52,1264,BLBD,2026-03-11,52|57|91,91,Financial Statements and Exhibits
53,1316,AXON,2026-03-11,52,52,Departure of Directors or Certain Officers; El...
54,1393,AJG,2026-03-12,52,52,Departure of Directors or Certain Officers; El...

,None,ticker,date,eventcodes,events,eventname
2,122,VG,2026-03-13,11|23|81|91,11,Entry into a Material Definitive Agreement
34,979,FANG,2026-03-12,11|81|91,11,Entry into a Material Definitive Agreement
42,1108,CTAS,2026-03-11,11|71|81|91,11,Entry into a Material Definitive Agreement